version: '2.4'
services:
  iris:
    image: iris-fhir-psn-proxy:0.1
    restart: unless-stopped
    ports: 
      - "9091:1972"
      - "9092:52773"
    command: --check-caps false
    #volumes:
    #  - ./:/irisrun/repo
    cpuset: "0-3"