Class FHIRPROXYPKG.Message.PayloadProcessResponse Extends Ens.Response
{

Property ProcessedResponse As HS.FHIRServer.Interop.Response;

Storage Default
{
<Data name="PayloadProcessResponseDefaultData">
<Subscript>"PayloadProcessResponse"</Subscript>
<Value name="1">
<Value>ProcessedResponse</Value>
</Value>
</Data>
<DefaultData>PayloadProcessResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}

